# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-09 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_auto_20170312_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
