# Generated by Django 4.1.1 on 2022-09-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_log_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
